/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Bálint' at '2017.02.20. 10:39' with Gradle 2.13
 *
 * @author Bálint, @date 2017.02.20. 10:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public boolean otherLibraryMethod() {
    	return false;
    }
}
