language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/app/.gradle

before_install:
  - cd app
  - chmod +x gradlew
 
before_script:
  - git fetch
  - git checkout -b build_branch
  - git merge origin/master

script:
  - ./gradlew build
